server {
    listen       LISTEN_PORT;
    server_name  localhost;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Markdown Negotiation
    location = / {
        if ($http_accept ~* "text/markdown") {
            rewrite ^/$ /index.md last;
        }
        add_header Link '</.well-known/api-catalog>; rel="api-catalog"';
    }

    location = /index.md {
        add_header Content-Type text/markdown;
        add_header x-markdown-tokens "v1";
    }

    # API Catalog with specific content type
    location = /.well-known/api-catalog {
        add_header Content-Type application/linkset+json;
    }

    # Agent Discovery Headers
    location / {
        add_header Link '</.well-known/api-catalog>; rel="api-catalog"';
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
